db.driverClassName=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/course_evaluation?useSSL=false&serverTimezone=UTC
db.username=root
db.password=Admin@Jos123!

mail.host=smtp.gmail.com
mail.port=587
mail.username=sangwajozaphat@gmail.com
mail.password=ipnv tkou hswj urvn
mail.from=no-reply@course-evaluation.local
mail.auth=true
mail.starttls=true

app.baseUrl=http://localhost:8080/course-evaluation
